### ISSUE TITLE
Check Nuggets routing in code

### ISSUE THREAD

**Issue by ArshdeepSahni** [sidthesloth92/db-portfolio#2]
**Nuggets** is giving an `error` when trying to open
<table><tr><th><img width="983" alt="Screen Shot 2020-12-02 at 12 14 33 AM" src="https://user-images.githubusercontent.com/56549294/100783316-a029c300-3433-11eb-83d9-03c53d0d67da.png"/></th></tr></table>

**Comment by sidthesloth92** [comment]
Should be fixed now.
